<?php

########################################################################
# Extension Manager/Repository config file for ext: "hrinewsletter"
#
# Auto generated by Extension Builder 2012-07-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'hr-interactive Newsletter',
	'description' => 'Interface to integrate the newsletter solution of hr-interactive to TYPO3',
	'category' => 'plugin',
	'author' => 'Ralf Schneider',
	'author_email' => 'ralf@hr-interactive.de',
	'author_company' => 'hr-interactive',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>